### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by Hell01World** [LinuxCafeFederation/awesome-android#79]
Hello! 

I would like to at these apps to this repository:

- AntennaPod
- BatteryBot
- DeepL
- Feeder
- FFShare
- Forecastie
- Just (Video) Player
- Markor
- MJ PDF Reader
- Mull
- Openreads
- Simple Time Tracker
- SimplyTranslate Mobile
- Sobriety

...but I don't know if this list is still maintained, since the last update was 8 months ago. Could you comment on this issue, so that I know that this repo is not abandoned?

**Comment by CipherOps** [comment]
Sorry, yes, this is still maintained. 

Since the last update I've got a full-time job and life stuff so not as much time to devote to this anymore.

This is just a mirror, the project is maintained at https://gitlab.com/linuxcafefederation/awesome-android

You can submit a PR there and I'll accept it.
